# DHCP server for WiFi Access Point (uap0)
# Separate dnsmasq instance, DNS disabled (port=0)
port=0
interface=uap0
bind-interfaces
dhcp-range=10.10.10.100,10.10.10.199,255.255.255.0,12h
dhcp-option=option:router,10.10.10.1
dhcp-option=option:dns-server,10.10.10.1
dhcp-leasefile=/var/lib/misc/dnsmasq-ap.leases
