KERNEL_DEVICETREE:append = " freescale/imx8mp-verdin-nonwifi-maivin.dtb"
KERNEL_DEVICETREE:append = " freescale/imx8mp-verdin-wifi-maivin.dtb"

MACHINE_EXTRA_RRECOMMENDS:append = " kernel-module-mdio-netlink"
MACHINE_EXTRA_RRECOMMENDS:append = " kernel-module-isp-vvcam"
MACHINE_EXTRA_RRECOMMENDS:append = " kernel-module-imx-gpu-viv"
MACHINE_EXTRA_RRECOMMENDS:append = " kernel-module-dp83tg720"
MACHINE_EXTRA_RRECOMMENDS:append = " kernel-module-uiodma"
